// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "DebugDrawer",
    platforms: [.macOS(.v15)],
    products: [
        .library(name: "DebugDrawer", targets: ["DebugDrawer"]),
        .library(name: "DebugDrawerConsolePlugin", targets: ["DebugDrawerConsolePlugin"]),
        .library(name: "DebugDrawerViewInspectorPlugin", targets: ["DebugDrawerViewInspectorPlugin"]),
        .library(name: "DebugDrawerAccessibilityPlugin", targets: ["DebugDrawerAccessibilityPlugin"]),
        .library(name: "DebugDrawerAppInfoPlugin", targets: ["DebugDrawerAppInfoPlugin"]),
        .library(name: "DebugDrawerUserDefaultsPlugin", targets: ["DebugDrawerUserDefaultsPlugin"]),
        .library(name: "DebugDrawerPerformancePlugin", targets: ["DebugDrawerPerformancePlugin"]),
        .library(name: "DebugDrawerNetworkPlugin", targets: ["DebugDrawerNetworkPlugin"]),
        .library(name: "DebugDrawerKeychainPlugin", targets: ["DebugDrawerKeychainPlugin"]),
        .library(name: "DebugDrawerScreenshotPlugin", targets: ["DebugDrawerScreenshotPlugin"]),
        .library(name: "DebugDrawerFileBrowserPlugin", targets: ["DebugDrawerFileBrowserPlugin"]),
        .library(name: "DebugDrawerDiskIOPlugin", targets: ["DebugDrawerDiskIOPlugin"]),
        .library(name: "DebugDrawerEnergyPlugin", targets: ["DebugDrawerEnergyPlugin"]),
    ],
    dependencies: [
        .package(url: "https://github.com/CheekyGhost-Labs/OSLogClient", from: "2.0.0"),
    ],
    targets: [
        .target(name: "DebugDrawer", path: "Sources/DebugDrawer"),
        .target(name: "DebugDrawerConsolePlugin",
                dependencies: ["DebugDrawer", .product(name: "OSLogClient", package: "OSLogClient")],
                path: "Sources/DebugDrawerConsolePlugin"),
        .target(name: "DebugDrawerViewInspectorPlugin",
                dependencies: ["DebugDrawer"],
                path: "Sources/DebugDrawerViewInspectorPlugin"),
        .target(name: "DebugDrawerAccessibilityPlugin",
                dependencies: ["DebugDrawer"],
                path: "Sources/DebugDrawerAccessibilityPlugin"),
        .target(name: "DebugDrawerAppInfoPlugin",
                dependencies: ["DebugDrawer"],
                path: "Sources/DebugDrawerAppInfoPlugin"),
        .target(name: "DebugDrawerUserDefaultsPlugin",
                dependencies: ["DebugDrawer"],
                path: "Sources/DebugDrawerUserDefaultsPlugin"),
        .target(name: "DebugDrawerPerformancePlugin",
                dependencies: ["DebugDrawer"],
                path: "Sources/DebugDrawerPerformancePlugin"),
        .target(name: "DebugDrawerNetworkPlugin",
                dependencies: ["DebugDrawer"],
                path: "Sources/DebugDrawerNetworkPlugin"),
        .target(name: "DebugDrawerKeychainPlugin",
                dependencies: ["DebugDrawer"],
                path: "Sources/DebugDrawerKeychainPlugin"),
        .target(name: "DebugDrawerScreenshotPlugin",
                dependencies: ["DebugDrawer"],
                path: "Sources/DebugDrawerScreenshotPlugin"),
        .target(name: "DebugDrawerFileBrowserPlugin",
                dependencies: ["DebugDrawer"],
                path: "Sources/DebugDrawerFileBrowserPlugin"),
        .target(name: "DebugDrawerDiskIOPlugin",
                dependencies: ["DebugDrawer"],
                path: "Sources/DebugDrawerDiskIOPlugin"),
        .target(name: "DebugDrawerEnergyPlugin",
                dependencies: ["DebugDrawer"],
                path: "Sources/DebugDrawerEnergyPlugin",
                linkerSettings: [.linkedFramework("IOKit")]),
        .testTarget(name: "DebugDrawerTests",
                    dependencies: ["DebugDrawer"],
                    path: "Tests/DebugDrawerTests"),
    ]
)
