// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "DebugDrawer",
    platforms: [.macOS(.v15), .iOS(.v17)],
    products: [
        .library(name: "DebugDrawer", targets: ["DebugDrawer"]),
        .library(name: "DebugDrawerConsolePlugin", targets: ["DebugDrawerConsolePlugin"]),
        .library(name: "DebugDrawerViewInspectorPlugin", targets: ["DebugDrawerViewInspectorPlugin"]),
        .library(name: "DebugDrawerAccessibilityPlugin", targets: ["DebugDrawerAccessibilityPlugin"]),
        .library(name: "DebugDrawerAppInfoPlugin", targets: ["DebugDrawerAppInfoPlugin"]),
        .library(name: "DebugDrawerUserDefaultsPlugin", targets: ["DebugDrawerUserDefaultsPlugin"]),
        .library(name: "DebugDrawerPerformancePlugin", targets: ["DebugDrawerPerformancePlugin"]),
        .library(name: "DebugDrawerNetworkPlugin", targets: ["DebugDrawerNetworkPlugin"]),
        .library(name: "DebugDrawerKeychainPlugin", targets: ["DebugDrawerKeychainPlugin"]),
        .library(name: "DebugDrawerScreenshotPlugin", targets: ["DebugDrawerScreenshotPlugin"]),
        .library(name: "DebugDrawerFileBrowserPlugin", targets: ["DebugDrawerFileBrowserPlugin"]),
        .library(name: "DebugDrawerDiskIOPlugin", targets: ["DebugDrawerDiskIOPlugin"]),
        .library(name: "DebugDrawerEnergyPlugin", targets: ["DebugDrawerEnergyPlugin"]),
    ],
    dependencies: [
        .package(url: "https://github.com/CheekyGhost-Labs/OSLogClient", from: "2.0.0"),
        // Test dependencies
        .package(url: "https://github.com/nalexn/ViewInspector", from: "0.10.0"),
        .package(url: "https://github.com/pointfreeco/swift-snapshot-testing", from: "1.17.0"),
        .package(url: "https://github.com/Tyler-Keith-Thompson/DependencyInjection", from: "1.0.12"),
        .package(url: "https://github.com/Kolos65/Mockable", from: "0.3.0"),
    ],
    targets: [
        // ── Library targets ─────────────────────────────────────────
        .target(name: "DebugDrawer", path: "Sources/DebugDrawer"),
        .target(name: "DebugDrawerConsolePlugin",
                dependencies: ["DebugDrawer", .product(name: "OSLogClient", package: "OSLogClient")],
                path: "Sources/DebugDrawerConsolePlugin"),
        .target(name: "DebugDrawerViewInspectorPlugin",
                dependencies: ["DebugDrawer"],
                path: "Sources/DebugDrawerViewInspectorPlugin"),
        .target(name: "DebugDrawerAccessibilityPlugin",
                dependencies: ["DebugDrawer"],
                path: "Sources/DebugDrawerAccessibilityPlugin"),
        .target(name: "DebugDrawerAppInfoPlugin",
                dependencies: ["DebugDrawer"],
                path: "Sources/DebugDrawerAppInfoPlugin"),
        .target(name: "DebugDrawerUserDefaultsPlugin",
                dependencies: ["DebugDrawer"],
                path: "Sources/DebugDrawerUserDefaultsPlugin"),
        .target(name: "DebugDrawerPerformancePlugin",
                dependencies: ["DebugDrawer"],
                path: "Sources/DebugDrawerPerformancePlugin"),
        .target(name: "DebugDrawerNetworkPlugin",
                dependencies: ["DebugDrawer"],
                path: "Sources/DebugDrawerNetworkPlugin"),
        .target(name: "DebugDrawerKeychainPlugin",
                dependencies: ["DebugDrawer"],
                path: "Sources/DebugDrawerKeychainPlugin"),
        .target(name: "DebugDrawerScreenshotPlugin",
                dependencies: ["DebugDrawer"],
                path: "Sources/DebugDrawerScreenshotPlugin"),
        .target(name: "DebugDrawerFileBrowserPlugin",
                dependencies: ["DebugDrawer"],
                path: "Sources/DebugDrawerFileBrowserPlugin"),
        .target(name: "DebugDrawerDiskIOPlugin",
                dependencies: ["DebugDrawer"],
                path: "Sources/DebugDrawerDiskIOPlugin"),
        .target(name: "DebugDrawerEnergyPlugin",
                dependencies: ["DebugDrawer"],
                path: "Sources/DebugDrawerEnergyPlugin",
                linkerSettings: [.linkedFramework("IOKit", .when(platforms: [.macOS]))]),

        // ── Test targets (per plugin) ───────────────────────────────
        .testTarget(name: "DebugDrawerTests",
                    dependencies: ["DebugDrawer"],
                    path: "Tests/DebugDrawerTests"),
        .testTarget(name: "DebugDrawerConsolePluginTests",
                    dependencies: ["DebugDrawerConsolePlugin", "DebugDrawer",
                                   .product(name: "ViewInspector", package: "ViewInspector"),
                                   .product(name: "SnapshotTesting", package: "swift-snapshot-testing")],
                    path: "Tests/DebugDrawerConsolePluginTests"),
        .testTarget(name: "DebugDrawerViewInspectorPluginTests",
                    dependencies: ["DebugDrawerViewInspectorPlugin", "DebugDrawer",
                                   .product(name: "ViewInspector", package: "ViewInspector"),
                                   .product(name: "SnapshotTesting", package: "swift-snapshot-testing")],
                    path: "Tests/DebugDrawerViewInspectorPluginTests"),
        .testTarget(name: "DebugDrawerAccessibilityPluginTests",
                    dependencies: ["DebugDrawerAccessibilityPlugin", "DebugDrawer",
                                   .product(name: "ViewInspector", package: "ViewInspector"),
                                   .product(name: "SnapshotTesting", package: "swift-snapshot-testing")],
                    path: "Tests/DebugDrawerAccessibilityPluginTests"),
        .testTarget(name: "DebugDrawerAppInfoPluginTests",
                    dependencies: ["DebugDrawerAppInfoPlugin", "DebugDrawer",
                                   .product(name: "ViewInspector", package: "ViewInspector")],
                    path: "Tests/DebugDrawerAppInfoPluginTests"),
        .testTarget(name: "DebugDrawerUserDefaultsPluginTests",
                    dependencies: ["DebugDrawerUserDefaultsPlugin", "DebugDrawer"],
                    path: "Tests/DebugDrawerUserDefaultsPluginTests"),
        .testTarget(name: "DebugDrawerPerformancePluginTests",
                    dependencies: ["DebugDrawerPerformancePlugin", "DebugDrawer"],
                    path: "Tests/DebugDrawerPerformancePluginTests"),
        .testTarget(name: "DebugDrawerNetworkPluginTests",
                    dependencies: ["DebugDrawerNetworkPlugin", "DebugDrawer",
                                   .product(name: "SnapshotTesting", package: "swift-snapshot-testing")],
                    path: "Tests/DebugDrawerNetworkPluginTests"),
        .testTarget(name: "DebugDrawerKeychainPluginTests",
                    dependencies: ["DebugDrawerKeychainPlugin", "DebugDrawer"],
                    path: "Tests/DebugDrawerKeychainPluginTests"),
        .testTarget(name: "DebugDrawerScreenshotPluginTests",
                    dependencies: ["DebugDrawerScreenshotPlugin", "DebugDrawer"],
                    path: "Tests/DebugDrawerScreenshotPluginTests"),
        .testTarget(name: "DebugDrawerFileBrowserPluginTests",
                    dependencies: ["DebugDrawerFileBrowserPlugin", "DebugDrawer"],
                    path: "Tests/DebugDrawerFileBrowserPluginTests"),
        .testTarget(name: "DebugDrawerDiskIOPluginTests",
                    dependencies: ["DebugDrawerDiskIOPlugin", "DebugDrawer"],
                    path: "Tests/DebugDrawerDiskIOPluginTests"),
        .testTarget(name: "DebugDrawerEnergyPluginTests",
                    dependencies: ["DebugDrawerEnergyPlugin", "DebugDrawer"],
                    path: "Tests/DebugDrawerEnergyPluginTests",
                    linkerSettings: [.linkedFramework("IOKit", .when(platforms: [.macOS]))]),
    ]
)
